/*
 * AT86RF212B_Constants.h
 *
 *  Created on: Feb 17, 2018
 *      Author: owner
 */

#ifndef MYINC_AT86RF212B_CONSTANTS_H_
#define MYINC_AT86RF212B_CONSTANTS_H_

#define 	ACK_DISABLE   1
#define 	ACK_ENABLE   0
#define 	ACK_TIME_12_SYMBOLS   0
#define 	ACK_TIME_2_SYMBOLS   1
#define 	AES_CTRL   (0x83)
#define 	AES_CTRL_MIRROR   (0x94)
#define 	AES_DIR_DECRYPT   (0x08)
#define 	AES_DIR_ENCRYPT   (0)
#define 	AES_MODE_CBC   (0x20)
#define 	AES_MODE_ECB   (0x0)
#define 	AES_MODE_KEY   (0x10)
#define 	AES_REQUEST   (0x80)
#define 	AES_RY_DONE   (1)
#define 	AES_RY_NOT_DONE   (0)
#define 	AES_STATE_KEY   (0x84)
#define 	AES_STATUS   (0x82)
#define 	ALTRATE_100_KBPS_OR_250_KBPS   0
#define 	ALTRATE_200_KBPS_OR_500_KBPS   1
#define 	ALTRATE_400_KBPS_OR_1_MBPS   2
#define 	ALTRATE_ALSO400_KBPS_OR_1_MBPS   3
#define 	ANT_EXT_SW_DISABLE_PINS   0
#define 	ANT_EXT_SW_ENABLE_PINS   1
#define 	ANT_SEL_ANTENNA_0   0
#define 	ANT_SEL_ANTENNA_1   1
#define 	BATMON_NOT_VALID   0
#define 	BATMON_VALID   1
#define 	BLM_AVAILABLE   (1)
#define 	BUSY_RX   1
#define 	BUSY_RX_AACK   17
#define 	BUSY_RX_AACK_NOCLK   30
#define 	BUSY_TX   2
#define 	BUSY_TX_ARET   18
#define 	CCA_CH_BUSY   0
#define 	CCA_CH_IDLE   1
#define 	CCA_COMPLETED   1
#define 	CCA_MODE_0   0
#define 	CCA_MODE_1   1
#define 	CCA_MODE_2   2
#define 	CCA_MODE_3   3
#define 	CCA_ONGOING   0
#define 	CCA_START   1
#define 	CLEAR_PD   0
#define 	CLKM_16MHZ   5
#define 	CLKM_1_4MHZ   6
#define 	CLKM_1MHZ   1
#define 	CLKM_2MHZ   2
#define 	CLKM_4MHZ   3
#define 	CLKM_8MHZ   4
#define 	CLKM_NO_CLOCK   0
#define 	CLKM_SHA_DISABLE   0
#define 	CLKM_SHA_ENABLE   1
#define 	CLKM_SYMBOL_RATE   7
#define 	CMD_FORCE_PLL_ON   4
#define 	CMD_FORCE_TRX_OFF   3
#define 	CMD_NOP   0
#define 	CMD_PLL_ON   9
#define 	CMD_RX_AACK_ON   22
#define 	CMD_RX_ON   6
#define 	CMD_TRX_OFF   8
#define 	CMD_TX_ARET_ON   25
#define 	CMD_TX_START   2
#define 	CRC16_NOT_VALID   0
#define 	CRC16_VALID   1
#define 	FRAME_VERSION_00   0
#define 	FRAME_VERSION_01   1
#define 	FRAME_VERSION_012   2
#define 	FRAME_VERSION_IGNORED   3
#define 	IRQ_HIGH_ACTIVE   0
#define 	IRQ_LOW_ACTIVE   1
#define 	IRQ_MASK_MODE_OFF   0
#define 	IRQ_MASK_MODE_ON   1
#define 	P_ON   0
#define 	PAD_CLKM_2MA   0
#define 	PAD_CLKM_4MA   1
#define 	PAD_CLKM_6MA   2
#define 	PAD_CLKM_8MA   3
#define 	PAD_IO_2MA   0
#define 	PAD_IO_4MA   1
#define 	PAD_IO_6MA   2
#define 	PAD_IO_8MA   3
#define 	PART_NUM_AT86RF212   7
#define 	PLL_ON   9
#define 	PROM_MODE_DISABLE   0
#define 	PROM_MODE_ENABLE   1
#define 	RF212_RAM_SIZE   (0x80)
#define 	RG_AES_CTRL_MIRROR   (0x94)
#define 	RSSI_BASE_VAL_BPSK_20   (-100)
#define 	RSSI_BASE_VAL_BPSK_40   (-99)
#define 	RSSI_BASE_VAL_OQPSK_100   (-98)
#define 	RSSI_BASE_VAL_OQPSK_250   (-97)
#define 	RX_AACK_ON   22
#define 	RX_AACK_ON_NOCLK   29
#define 	RX_DISABLE   1
#define 	RX_ENABLE   0
#define 	RX_ON   6
#define 	RX_ON_NOCLK   28
#define 	RX_SAFE_MODE_DISABLE   0
#define 	RX_SAFE_MODE_ENABLE   1
#define 	SET_PD   1
#define 	SLEEP   15
#define 	SPI_CMD_MODE_DEFAULT   0
#define 	SPI_CMD_MODE_IRQ_STATUS   3
#define 	SPI_CMD_MODE_PHY_RSSI   2
#define 	SPI_CMD_MODE_TRX_STATUS   1
#define 	STATE_TRANSITION_IN_PROGRESS   31
#define 	T_OCT   32
#define 	T_SYM   16
#define 	TIMESTAMPING_DISABLE   0
#define 	TIMESTAMPING_ENABLE   1
#define 	TRAC_CHANNEL_ACCESS_FAILURE   3
#define 	TRAC_CHANNEL_ACCESS_FAILURE   (3)
#define 	TRAC_INVALID   7
#define 	TRAC_INVALID   (7)
#define 	TRAC_NO_ACK   5
#define 	TRAC_NO_ACK   (5)
#define 	TRAC_SUCCESS   0
#define 	TRAC_SUCCESS   (0)
#define 	TRAC_SUCCESS_DATA_PENDING   1
#define 	TRAC_SUCCESS_DATA_PENDING   (1)
#define 	TRAC_SUCCESS_WAIT_FOR_ACK   2
#define 	TRAC_SUCCESS_WAIT_FOR_ACK   (2)
#define 	TRX_AES_BLOCK_SIZE   (16)
#define 	TRX_IRQ_AMI   (0x20)
#define 	TRX_IRQ_AWAKE_END   (0x10)
#define 	TRX_IRQ_BAT_LOW   (0x80)
#define 	TRX_IRQ_CCA_ED_DONE   (0x10)
#define 	TRX_IRQ_CCA_ED_READY   (TRX_IRQ_CCA_ED_DONE)
#define 	TRX_IRQ_PLL_LOCK   (0x01)
#define 	TRX_IRQ_PLL_UNLOCK   (0x02)
#define 	TRX_IRQ_RX_START   (0x04)
#define 	TRX_IRQ_TRX_END   (0x08)
#define 	TRX_IRQ_TRX_UR   (0x40)
#define 	TRX_OFF   8
#define 	TX_ARET_ON   25
#define 	TX_AUTO_CRC_DISABLE   0
#define 	TX_AUTO_CRC_ENABLE   1
#define 	UPLD_RES_FT_DISABLE   0
#define 	UPLD_RES_FT_ENABLE   1
#define 	VERSION_NUM_AT86RF212   1

#endif /* MYINC_AT86RF212B_CONSTANTS_H_ */
